# Temel imaj olarak hafif bir Python sürümü seçiyoruz [cite: 100]
FROM python:3.9-slim

# Konteyner içindeki çalışma dizinini ayarlıyoruz [cite: 101]
WORKDIR /app

# Flask kütüphanesini kuruyoruz [cite: 102]
RUN pip install flask

# Çalıştığımız dizindeki app.py dosyasını konteynerin çalışma dizinine kopyalıyoruz [cite: 103]
COPY app.py .

# Konteyner ayağa kalktığında çalıştırılacak varsayılan komut [cite: 104]
CMD ["python", "app.py"]