# Temel imaj olarak hafif bir Python sürümü seçiyoruz 
FROM python:3.9-slim

# Konteyner içindeki çalışma dizinini ayarlıyoruz 
WORKDIR /app

# Flask kütüphanesini kuruyoruz 
RUN pip install flask

# Çalıştığımız dizindeki app.py dosyasını konteynerin çalışma dizinine kopyalıyoruz 
COPY app.py .

# Konteyner ayağa kalktığında çalıştırılacak varsayılan komut 
CMD ["python", "app.py"]